#!/usr/bin/python3
import sqlite3,sys

if len(sys.argv) != 2 :
  print("Usage:",sys.argv[0],"titles")
  sys.exit(1)

titles = sys.argv[1]

con = sqlite3.connect('a2.db')

query = """select m.title,m.year, m.content_rating, r.imdb_score,group_concat(genre.genre) from movie m 
  	join genre on genre.movie_id = m.id
	join rating r on r.movie_id = m.id
	where upper(m.title) like upper("%{}%")
	group by m.title
	order by m.year asc, r.imdb_score desc, m.title asc
  """
cur = con.cursor()
cur.execute(query.format(titles))
i = 1
flag = -1

while True:
	t = cur.fetchone()
	if t == None:
 		break
	flag = 1
	title,year,rating,score,genre = t
	if year == None:
		flag = 0
	else:
		if rating == None and score == None:
			print(str(i) + '. {} ({}) [{}]'.format(title,year,genre))
		elif rating != None and score == None:
			print(str(i) + '. {} ({}, {}) [{}]'.format(title,year,rating,genre))
		elif rating == None and score != None:
			print(str(i) + '. {} ({}, {:2.1f}) [{}]'.format(title,year,score,genre))
		elif rating != None and score != None:
			print(str(i) + '. {} ({}, {}, {:2.1f}) [{}]'.format(title,year,rating,score,genre))
	if flag == 1:
		i = i + 1

query2 = """select m.title,m.year, m.content_rating, r.imdb_score,group_concat(genre.genre) from movie m 
    join genre on genre.movie_id = m.id
	join rating r on r.movie_id = m.id
	where upper(m.title) like upper("%{}%") and m.year is null
	group by m.title
	order by r.imdb_score desc, m.title asc
  """
cur2 = con.cursor()
cur2.execute(query2.format(titles))


while True:
  t2 = cur2.fetchone()
  if t2 == None:
  	break
  title,year,rating,score,genre = t2
  if rating == None and score == None:
  	print(str(i) + '. {} [{}]'.format(title,genre))
  elif rating != None and score == None:
  	print(str(i) + '. {} ({}) [{}]'.format(title,rating,genre))
  elif rating == None and score != None:
  	print(str(i) + '. {} ({:2.1f}) [{}]'.format(title,score,genre))
  elif rating != None and score != None:
  	print(str(i) + '. {} ({}, {:2.1f}) [{}]'.format(title,rating,score,genre))
  i = i + 1



con.close()

